jobs:
  test:     
    runs-on: ubuntu-latest
    steps:
        - name: run test  
          run:  exit 1
  deploy:
    needs: test
    if: github.ref == 'ref/heads/main' && success()
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        run